apiVersion: kuberik.com/v1alpha1
kind: Rollout
metadata:
  name: hello-world-manifests
  annotations:
    dashboard.rollout.kuberik.com/description: "Hello World manifests / __ENVIRONMENT__"
spec:
  releasesImagePolicy:
    name: hello-world-manifests
  versionHistoryLimit: 5
  bakeTime: 15s
  healthCheckSelector:
    selector:
      matchLabels:
        app: hello-world
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hello-world-manifests
spec:
  image: ghcr.io/littlechimera/hello-world/__ENVIRONMENT__/manifests
  interval: 60s
  secretRef:
    name: github-registry-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: hello-world-manifests
spec:
  imageRepositoryRef:
    name: hello-world-manifests
  filterTags:
    pattern: "^main-(?P<timestamp>[0-9]+)-[a-f0-9]+$"
    extract: "$timestamp"
  policy:
    alphabetical:
      order: asc
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: hello-world
  annotations:
    rollout.kuberik.com/rollout: hello-world-manifests
spec:
  interval: 60s
  url: oci://ghcr.io/littlechimera/hello-world/__ENVIRONMENT__/manifests
  secretRef:
    name: github-registry-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-world
  annotations:
    rollout.kuberik.com/substitute.HELLO_WORLD_VERSION.from: "hello-world-app"
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: OCIRepository
    name: hello-world
---
apiVersion: kuberik.com/v1alpha1
kind: Rollout
metadata:
  name: hello-world-app
  labels:
    schedule: business-hours  # This rollout is controlled by business-hours schedule
  annotations:
    dashboard.rollout.kuberik.com/description: "Hello World app / __ENVIRONMENT__"
spec:
  releasesImagePolicy:
    name: hello-world-app
  versionHistoryLimit: 5
  bakeTime: 15s
  healthCheckSelector:
    selector:
      matchLabels:
        app: hello-world
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hello-world-app
spec:
  image: ghcr.io/littlechimera/hello-world/app
  interval: 60s
  secretRef:
    name: github-registry-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: hello-world-app
spec:
  imageRepositoryRef:
    name: hello-world-app
  filterTags:
    pattern: "^main-(?P<timestamp>[0-9]+)-[a-f0-9]+$"
    extract: "$timestamp"
  policy:
    alphabetical:
      order: asc
---
apiVersion: kuberik.com/v1alpha1
kind: HealthCheck
metadata:
  name: hello-world-kustomization-health-check
  labels:
    app: hello-world
  annotations:
    healthcheck.kuberik.com/kustomization: "hello-world"
    kuberik.com/display-name: "Flux Deployment"
spec:
  class: "kustomization"
---
apiVersion: environments.kuberik.com/v1alpha1
kind: Environment
metadata:
  name: hello-world-app
spec:
  # Reference to the Rollout that this Deployment manages
  rolloutRef:
    name: hello-world-app
  backend:
    type: github
    project: "LittleChimera/kuberik-testing"
    secret: "github-token"
  name: "hello-world-app"
---
# Example: Business hours deployment window
apiVersion: kuberik.com/v1alpha1
kind: RolloutSchedule
metadata:
  name: business-hours-allow
  annotations:
    gate.kuberik.com/pretty-name: "Business Hours Only"
    gate.kuberik.com/description: "Deployments allowed only during weekday business hours (9 AM - 5 PM EST)"
spec:
  rolloutSelector:
    matchLabels:
      schedule: business-hours
  rules:
    - name: "weekday-business-hours"
      timeRange:
        start: "09:00"
        end: "17:00"
      daysOfWeek:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
  timezone: "America/New_York"
  action: Allow
---
# Example: Weekend-only deployments
apiVersion: kuberik.com/v1alpha1
kind: RolloutSchedule
metadata:
  name: weekend-only
  annotations:
    gate.kuberik.com/pretty-name: "Weekend Deployments"
    gate.kuberik.com/description: "Deployments allowed only on weekends"
spec:
  rolloutSelector:
    matchLabels:
      schedule: weekend
  rules:
    - name: "weekend-deployment"
      daysOfWeek:
        - Saturday
        - Sunday
  timezone: "UTC"
  action: Allow
---
# Example: Night deployment window (cross-midnight)
apiVersion: kuberik.com/v1alpha1
kind: RolloutSchedule
metadata:
  name: night-deployment
  annotations:
    gate.kuberik.com/pretty-name: "Night Deployment Window"
    gate.kuberik.com/description: "Deployments allowed overnight (10 PM - 6 AM UTC)"
spec:
  rolloutSelector:
    matchLabels:
      schedule: night
  rules:
    - name: "overnight-window"
      timeRange:
        start: "22:00"
        end: "06:00"
      daysOfWeek:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
  timezone: "UTC"
  action: Allow
