apiVersion: kuberik.com/v1alpha1
kind: Rollout
metadata:
  name: hello-world-manifests
  annotations:
    dashboard.rollout.kuberik.com/description: "Hello World manifests / __ENVIRONMENT__"
spec:
  releasesImagePolicy:
    name: hello-world-manifests
  versionHistoryLimit: 5
  bakeTime: 15s
  healthCheckSelector:
    selector:
      matchLabels:
        app: hello-world
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hello-world-manifests
spec:
  image: ghcr.io/littlechimera/hello-world/__ENVIRONMENT__/manifests
  interval: 60s
  secretRef:
    name: github-registry-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: hello-world-manifests
spec:
  imageRepositoryRef:
    name: hello-world-manifests
  filterTags:
    pattern: "^main-(?P<timestamp>[0-9]+)-[a-f0-9]+$"
    extract: "$timestamp"
  policy:
    alphabetical:
      order: asc
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: hello-world
  annotations:
    rollout.kuberik.com/rollout: hello-world-manifests
spec:
  interval: 60s
  url: oci://ghcr.io/littlechimera/hello-world/__ENVIRONMENT__/manifests
  secretRef:
    name: github-registry-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-world
  annotations:
    rollout.kuberik.com/substitute.HELLO_WORLD_VERSION.from: "hello-world-app"
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: OCIRepository
    name: hello-world
---
apiVersion: kuberik.com/v1alpha1
kind: Rollout
metadata:
  name: hello-world-app
  annotations:
    dashboard.rollout.kuberik.com/description: "Hello World app / __ENVIRONMENT__"
spec:
  releasesImagePolicy:
    name: hello-world-app
  versionHistoryLimit: 5
  bakeTime: 15s
  healthCheckSelector:
    selector:
      matchLabels:
        app: hello-world
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hello-world-app
spec:
  image: ghcr.io/littlechimera/hello-world/app
  interval: 60s
  secretRef:
    name: github-registry-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: hello-world-app
spec:
  imageRepositoryRef:
    name: hello-world-app
  filterTags:
    pattern: "^main-(?P<timestamp>[0-9]+)-[a-f0-9]+$"
    extract: "$timestamp"
  policy:
    alphabetical:
      order: asc
---
apiVersion: kuberik.com/v1alpha1
kind: HealthCheck
metadata:
  name: hello-world-kustomization-health-check
  labels:
    app: hello-world
  annotations:
    healthcheck.kuberik.com/kustomization: "hello-world"
    kuberik.com/display-name: "Flux Deployment"
spec:
  class: "kustomization"
---
apiVersion: github.kuberik.com/v1alpha1
kind: GitHubDeployment
metadata:
  name: hello-world-app
spec:
  # Reference to the Rollout that this GitHubDeployment manages
  rolloutRef:
    name: hello-world-app

  # GitHub repository configuration
  # TODO: parametrize
  repository: "LittleChimera/rollout-example"
  deploymentName: "hello-world-app"

  # GitHub token configuration
  githubTokenSecret: "github-token"
