apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      kind: Service
      name: rollout-dashboard
      namespace: rollout-dashboard
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30951
      - op: replace
        path: /spec/type
        value: NodePort
