apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-dashboard
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: rollout-dashboard
      containers:
        - name: rollout-dashboard
          image: ko://github.com/kuberik/rollout-dashboard
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-dashboard
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollout-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rollout-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rollout-controller-manager-role
subjects:
  - kind: ServiceAccount
    name: rollout-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollout-dashboard-view
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rollout-dashboard-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rollout-dashboard-view
subjects:
  - kind: ServiceAccount
    name: rollout-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollout-dashboard-rollouts-patch
rules:
  - apiGroups: ["rollouts.kruise.io"]
    resources: ["rollouts/status"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rollout-dashboard-rollouts-patch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rollout-dashboard-rollouts-patch
subjects:
  - kind: ServiceAccount
    name: rollout-dashboard
