---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-python-script
data:
  app.py: |
    import os
    from http.server import BaseHTTPRequestHandler, HTTPServer

    VERSION = os.environ.get("VERSION", "unknown")

    class Handler(BaseHTTPRequestHandler):
        def do_GET(self):
            self.send_response(200)
            self.send_header("Content-type", "text/plain")
            self.end_headers()
            self.wfile.write(f"Hello, World!\nVersion: {VERSION}\n".encode())

    if __name__ == "__main__":
        port = int(os.environ.get("PORT", 8080))
        server = HTTPServer(("", port), Handler)
        print(f"Serving on port {port}")
        server.serve_forever()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  labels:
    app: hello-python
spec:
  minReadySeconds: 15
  replicas: 2
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
        - name: python-server
          image: ghcr.io/littlechimera/hello-world/app:${HELLO_WORLD_VERSION}
          command: ["python", "/app/app.py"]
          env:
            - name: VERSION
              value: ${HELLO_WORLD_VERSION}
            - name: PORT
              value: "8080"
            - name: DD_SERVICE
              value: hello-python
            - name: DD_ENV
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-script
              mountPath: /app/app.py
              subPath: app.py
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: app-script
          configMap:
            name: hello-python-script
---
apiVersion: rollouts.kruise.io/v1beta1
kind: Rollout
metadata:
  name: hello-python
  annotations:
    rollout.kuberik.io/step-1-max-wait: "10m"
    rollout.kuberik.io/step-1-min-wait-after-success: "30s"
spec:
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-python
  strategy:
    canary:
      steps:
      - replicas: 1
        traffic: 20%
        # pause:
        #   duration: 20
      - replicas: 100%
        # pause:
        #   duration: 20
      trafficRoutings:
        - service: hello-python
          gateway:
            httpRouteName: hello-python
---
apiVersion: rollout.kuberik.com/v1alpha1
kind: RolloutTest
metadata:
  name: hello-python-test
  labels:
    app: hello-python
spec:
  rolloutName: hello-python
  stepIndex: 1
  jobTemplate:
    backoffLimit: 1
    template:
      spec:
        restartPolicy: Never
        containers:
          - name: hello-python-test
            image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
            args: ["uv", "run", "/app/test.py"]
            env:
              - name: PORT
                value: "80"
            volumeMounts:
              - name: app-test-script
                mountPath: /app/test.py
                subPath: test.py
        volumes:
          - name: app-test-script
            configMap:
              name: hello-python-test-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-python-test-script
data:
  test.py: |
    # /// script
    # requires-python = ">=3.12"
    # dependencies = [
    #     "requests>=2.32.0",
    # ]
    # ///
    import os
    import requests
    import time

    def main():
      time.sleep(15)
      service_host = os.environ.get("SERVICE_HOST", "hello-python-canary")
      service_port = int(os.environ.get("PORT", "80"))
      url = f"http://{service_host}:{service_port}/"
      try:
        resp = requests.get(url, timeout=5)
        print("Response:", resp.status_code, resp.text)
        if resp.status_code != 200:
          print("Request failed")
          exit(1)
      except Exception as e:
        print("Request error:", e)
        exit(1)

    if __name__ == "__main__":
      main()
---
apiVersion: v1
kind: Service
metadata:
  name: hello-python
  labels:
    app: hello-python
spec:
  selector:
    app: hello-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hello-python-gateway
  namespace: hello-world
  labels:
    app: hello-python
spec:
  gatewayClassName: envoy
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: hello-python.example.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-python
  namespace: hello-world
  labels:
    app: hello-python
spec:
  parentRefs:
    - name: hello-python-gateway
  hostnames:
    - hello-python.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hello-python
          port: 80
---
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: hello-python-monitor
  namespace: hello-world
  annotations:
    kuberik.com/health-check: "true"
  labels:
    app.kubernetes.io/name: hello-python-monitor
    app.kubernetes.io/part-of: rollout-dashboard
    app.kubernetes.io/managed-by: kubectl
    app: hello-python
spec:
  message: "Auto-generated monitor for hello-python"
  query: "avg(last_1m):avg:system.cpu.idle{*} by {host} > 90"
  tags:
    - "env:dev"
  type: metric alert
  name: hello-python-monitor
